version: '3.8'
services:
  db:
    image: mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_DATABASE=db_bank_sampah
      - MYSQL_HOST=db
    secrets:
      - mysql_root_password
  app:
    build: .
    ports:
      - '3000:5173'
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
    env_file:
      - ./.env
    depends_on:
      - db

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt

volumes:
  db_data:
